### ISSUE TITLE
Seems to be broken

### ISSUE THREAD

**Issue by LacikIgor** [addyosmani/polymer-ui-carousel#10]
Hello, 

maybe there is a new version of polymer out, but I am not able to run your carousel.

1. After installation with bower, I had some path problems, so had to change lines 39-42 from
path. Eg.: bower_components/polymer-animation to ../polymer-animation
2. Now I am receiving an error:  Uncaught ReferenceError: AnimationGroup is not defined polymer-animation-group.html

Thx for the attempt :)

Best wishes :)

**Comment by addyosmani** [comment]
Current repo is indeed broken. I'll rewrite it this evening.
